
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
    "age": 20,
    "password": "n0ki3er.0proVa23lc$dIgo",
    "city": "Madrid",
    "hobbies": ["Restaurante", "Museo", "Fútbol"],
    "openToOffers": true
}

###

POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Pepito",
    "email": "peitoperez@test.com",
    "age": 30,
    "password": "3stoN0.esuN4contr4s3ña",
    "city": "Barcelona",
    "hobbies": ["Restaurante", "Aviones", "Rugby"]
}

###

POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Almudena",
    "email": "almudenagimenez@test.com",
    "age": 9,
    "password": "holaef.A1a",
    "city": "Bilbao",
    "hobbies": ["Fútbol", "Aviones", "Rugby"]
}
###

POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "menganitohernandez@test.com",
    "password": "n0ki3er.0proVa23lc$dIgo"
}


### ADMIN

POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "peitoperez@test.com",
    "password": "3stoN0.esuN4contr4s3ña"
}

###

POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "almudenagimenez@test.com",
    "password": "gjubwbig2492.ramgler,g"
}

### Obtener todos los users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFmZjk5ZjhiZWFiMWUyOGY0MGMxYjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzIyMDU3MDgsImV4cCI6MTczMjI5MjEwOH0.KXUtc6DJWu6WZl_rDvEW3RHzFwB7hy3sltn2rJuTQjw

### Obtener una página users por su ID
GET http://localhost:3000/api/users/6717c999d065ac2a9d4f0b94
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzE3YjVlYjc2NmVlNTNhNzE1MmVhYTgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjk3ODY2MjAsImV4cCI6MTcyOTg3MzAyMH0.EPRj6L4WYIs1Ea6MzeU42kAQwhxWHUYIpCp0twNzYSM

### Deja porque es el token de Menganito y no intenta cambiar el rol

PUT http://localhost:3000/api/users/673cb1c25c3fdb2aaf951ba4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFmZjk5ZjhiZWFiMWUyOGY0MGMxYjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzIyMDU3MDgsImV4cCI6MTczMjI5MjEwOH0.KXUtc6DJWu6WZl_rDvEW3RHzFwB7hy3sltn2rJuTQjw

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
    "age": 64,
    "city": "Madrid",
    "hobbies": ["Restaurante", "Museo", "Fútbol"],
    "openToOffers": true
}

### No deja porque el token es de Almudena y no es admin

PUT http://localhost:3000/api/users/6717ca80d065ac2a9d4f0b9f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzE3Yzk5OWQwNjVhYzJhOWQ0ZjBiOTQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcyOTYxMjUwNiwiZXhwIjoxNzI5Njk4OTA2fQ.isuesU1FxteVxq6VQeBwdQEAOweEG6xbE6v1uGS1HBQ

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
    "age": 64,
    "city": "Madrid",
    "hobbies": ["Restaurante", "Museo", "Fútbol"],
    "openToOffers": true
}

### Deja porque el token es de admin y también podría cambiar el rol

PUT http://localhost:3000/api/users/6717ca80d065ac2a9d4f0b9f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzE3YjVlYjc2NmVlNTNhNzE1MmVhYTgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjk2MTI1NTgsImV4cCI6MTcyOTY5ODk1OH0.Yprt2OkgzTDaJyTWnp1zIErtsmp3k6aPP6QcMOMNQjk

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
    "age": 64,
    "city": "Madrid",
    "hobbies": ["Restaurante", "Museo", "Fútbol"],
    "openToOffers": true
}


### Archivar un user (borrado lógico)
DELETE http://localhost:3000/api/users/6717ca80d065ac2a9d4f0b9f?logic=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFmZjk5ZjhiZWFiMWUyOGY0MGMxYjUiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMDE0ODc2NywiZXhwIjoxNzMwMjM1MTY3fQ.XHwRxheJkRNpMzr8irlPNYp07cnsMrO9V4jagOORnjs

### Llamada para restaurar un borrado lógico
PUT http://localhost:3000/api/users/restore/6717ca80d065ac2a9d4f0b9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFmZjk5ZjhiZWFiMWUyOGY0MGMxYjUiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMDE0ODc2NywiZXhwIjoxNzMwMjM1MTY3fQ.XHwRxheJkRNpMzr8irlPNYp07cnsMrO9V4jagOORnjs


### Eliminar un user (borrado físico)
DELETE http://localhost:3000/api/users/671fb460afda9b6f5ac5576e?logic=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFmZjk5ZjhiZWFiMWUyOGY0MGMxYjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzAzMDk0MzUsImV4cCI6MTczMDM5NTgzNX0.Hy2Kaxpz9G0LAdk2E8rSIJuYelrVpLKxjZhVAZsbotI